/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoommatesRouteImport } from './routes/roommates'
import { Route as RoommateSurveyRouteImport } from './routes/roommate-survey'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddListingRouteImport } from './routes/add-listing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as RoommateIdRouteImport } from './routes/roommate.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesRoute = RoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommateSurveyRoute = RoommateSurveyRouteImport.update({
  id: '/roommate-survey',
  path: '/roommate-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddListingRoute = AddListingRouteImport.update({
  id: '/add-listing',
  path: '/add-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const RoommateIdRoute = RoommateIdRouteImport.update({
  id: '/roommate/$id',
  path: '/roommate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/roommate-survey': typeof RoommateSurveyRoute
  '/roommates': typeof RoommatesRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/roommate/$id': typeof RoommateIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/roommate-survey': typeof RoommateSurveyRoute
  '/roommates': typeof RoommatesRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/roommate/$id': typeof RoommateIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/roommate-survey': typeof RoommateSurveyRoute
  '/roommates': typeof RoommatesRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/roommate/$id': typeof RoommateIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-listing'
    | '/auth'
    | '/help'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/roommate-survey'
    | '/roommates'
    | '/search'
    | '/welcome'
    | '/chat/$id'
    | '/listing/$id'
    | '/roommate/$id'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-listing'
    | '/auth'
    | '/help'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/roommate-survey'
    | '/roommates'
    | '/search'
    | '/welcome'
    | '/chat/$id'
    | '/listing/$id'
    | '/roommate/$id'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/add-listing'
    | '/auth'
    | '/help'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/roommate-survey'
    | '/roommates'
    | '/search'
    | '/welcome'
    | '/chat/$id'
    | '/listing/$id'
    | '/roommate/$id'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddListingRoute: typeof AddListingRoute
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RoommateSurveyRoute: typeof RoommateSurveyRoute
  RoommatesRoute: typeof RoommatesRoute
  SearchRoute: typeof SearchRoute
  WelcomeRoute: typeof WelcomeRoute
  ListingIdRoute: typeof ListingIdRoute
  RoommateIdRoute: typeof RoommateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates': {
      id: '/roommates'
      path: '/roommates'
      fullPath: '/roommates'
      preLoaderRoute: typeof RoommatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommate-survey': {
      id: '/roommate-survey'
      path: '/roommate-survey'
      fullPath: '/roommate-survey'
      preLoaderRoute: typeof RoommateSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-listing': {
      id: '/add-listing'
      path: '/add-listing'
      fullPath: '/add-listing'
      preLoaderRoute: typeof AddListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/roommate/$id': {
      id: '/roommate/$id'
      path: '/roommate/$id'
      fullPath: '/roommate/$id'
      preLoaderRoute: typeof RoommateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddListingRoute: AddListingRoute,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RoommateSurveyRoute: RoommateSurveyRoute,
  RoommatesRoute: RoommatesRoute,
  SearchRoute: SearchRoute,
  WelcomeRoute: WelcomeRoute,
  ListingIdRoute: ListingIdRoute,
  RoommateIdRoute: RoommateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
